project_name: argo-helper

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/rebelopsio/argo-helper/cmd.version={{.Version}} -X github.com/rebelopsio/argo-helper/cmd.commit={{.Commit}} -X github.com/rebelopsio/argo-helper/cmd.buildDate={{.Date}}
    binary: "{{ .ProjectName }}"

archives:
  - format: tar.gz
    # This is a workaround for windows users using "tar.gz" vs "zip"
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
      - docs/**/*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

brews:
  - tap:
      owner: rebelopsio
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/rebelopsio/argo-helper
    description: A CLI tool to help bootstrap and manage ArgoCD repositories
    license: MIT
    test: |
      system "#{bin}/argo-helper --version"
    install: |
      bin.install "argo-helper"

dockers:
  - image_templates:
      - "rebelopsio/argo-helper:{{ .Version }}"
      - "rebelopsio/argo-helper:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"