apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-by-list
  namespace: argocd
spec:
  generators:
    - list:  # Use a list generator for explicitly defined applications
        elements:
          - name: app1
            namespace: app1-ns
            environment: dev
          - name: app2
            namespace: app2-ns
            environment: staging
          - name: app3
            namespace: app3-ns
            environment: production
  template:
    metadata:
      name: '{{`{{ name }}`}}'
      labels:
        environment: '{{`{{ environment }}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/yourorg/your-repo.git
        targetRevision: HEAD
        path: apps/{{`{{ name }}`}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{`{{ namespace }}`}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true